import Link from "next/link";
import { ArrowRight, Camera, Clock3, MapPin, ShieldCheck, Star } from "lucide-react";

import { BrandMark } from "@/components/brand-mark";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { business, services, staff } from "@/data/demo";

export default async function BusinessPage({ params }: { params: Promise<{ slug: string }> }) {
  await params;
  return (
    <main className="min-h-screen bg-background">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><Link href="/"><BrandMark /></Link><div className="flex items-center gap-2"><Button asChild variant="ghost" size="sm" className="hidden sm:inline-flex"><a href="https://www.instagram.com" target="_blank" rel="noreferrer"><Camera data-icon="inline-start" /> Instagram</a></Button><Button asChild><Link href={`/barbearia/${business.slug}/agendar`}>Agendar agora <ArrowRight data-icon="inline-end" /></Link></Button></div></nav>
      <section className="relative mx-auto max-w-7xl overflow-hidden px-5 pb-10 pt-8 lg:px-8 lg:pb-20 lg:pt-16">
        <div className="absolute inset-x-[20%] top-0 -z-10 h-72 rounded-full bg-primary/15 blur-3xl" />
        <div className="grid items-center gap-12 lg:grid-cols-[1fr_.8fr]">
          <div><Badge variant="outline" className="mb-6 border-primary/30 bg-primary/8 text-primary"><span className="mr-1 size-1.5 rounded-full bg-[#B7F34A]" /> Bruxelas · Desde 2018</Badge><h1 className="font-heading text-balance text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl">Precisão no corte. <span className="text-primary">Calma no ritual.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Barbearia contemporânea no coração de Bruxelas. Uma equipe experiente, técnicas clássicas e o tempo certo para você.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12"><Link href={`/barbearia/${business.slug}/agendar`}>Escolher meu horário <ArrowRight data-icon="inline-end" /></Link></Button><Button asChild variant="outline" size="lg" className="h-12"><a href="https://www.google.com/maps/search/?api=1&query=Rue+Antoine+Dansaert+74+Bruxelles" target="_blank" rel="noreferrer"><MapPin data-icon="inline-start" /> Como chegar</a></Button></div><div className="mt-8 flex flex-wrap gap-5 text-sm text-muted-foreground"><span className="flex items-center gap-2"><Star className="size-4 fill-amber-400 text-amber-400" /> {business.rating} ({business.reviews} avaliações)</span><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" /> Reserva protegida por sinal</span></div></div>
          <div className="relative min-h-[420px] overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle_at_30%_20%,rgba(196,181,253,.25),transparent_25%),linear-gradient(145deg,#1c1825,#0d0d11_64%)] p-6 shadow-2xl">
            <div className="absolute -right-20 -top-10 size-64 rounded-full border-[42px] border-primary/10" /><div className="absolute bottom-0 left-[18%] top-0 w-px rotate-[24deg] bg-gradient-to-b from-transparent via-primary/60 to-transparent" />
            <div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-primary">AS / BRU</p><p className="font-heading mt-2 text-2xl font-semibold">A cadeira está pronta.</p></div><span className="font-heading text-7xl font-semibold text-white/[.035]">AS</span></div><div className="mt-48 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-black/25 p-4 backdrop-blur"><Clock3 className="mb-4 text-primary" /><p className="font-heading text-lg font-semibold">Aberto hoje</p><p className="text-xs text-muted-foreground">09:00 — 19:00</p></div><div className="rounded-2xl bg-primary p-4 text-primary-foreground"><p className="text-xs opacity-75">Próximo horário</p><p className="font-heading mt-4 text-3xl font-semibold">13:15</p><p className="text-xs opacity-75">com Lucas</p></div></div></div>
          </div>
        </div>
      </section>

      <section className="border-y border-white/8 bg-white/[.015]"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-16 lg:grid-cols-[.55fr_1fr] lg:px-8"><div><p className="text-xs font-medium uppercase tracking-[.2em] text-primary">Menu de serviços</p><h2 className="font-heading mt-3 text-3xl font-semibold tracking-[-.04em]">Escolha seu ritual.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Todos os serviços incluem consulta rápida e recomendação de manutenção.</p></div><div className="flex flex-col">{services.map((service) => <Link key={service.id} href={`/barbearia/${business.slug}/agendar?servico=${service.id}`} className="group flex items-center justify-between gap-5 border-b border-white/8 py-5 first:pt-0 last:border-0"><div><div className="flex items-center gap-2"><p className="font-heading text-lg font-medium group-hover:text-primary">{service.name}</p>{service.popular ? <Badge>Mais pedido</Badge> : null}</div><p className="mt-1 text-xs text-muted-foreground">{service.description} · {service.duration} min</p></div><div className="flex items-center gap-4"><span className="font-mono text-sm">€ {service.price}</span><ArrowRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div></Link>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8 lg:py-24"><div className="mb-9 flex items-end justify-between"><div><p className="text-xs font-medium uppercase tracking-[.2em] text-primary">A equipe</p><h2 className="font-heading mt-3 text-3xl font-semibold">Quem cuida do seu estilo.</h2></div><p className="hidden max-w-sm text-right text-sm text-muted-foreground sm:block">Quatro profissionais, uma mesma obsessão por acabamento.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{staff.map((member) => <Card key={member.id} className="group border-white/8"><CardContent className="p-5"><div className="mb-12 flex justify-between"><Avatar className="size-12"><AvatarFallback style={{ color: member.color, backgroundColor: `${member.color}1c` }}>{member.initials}</AvatarFallback></Avatar><span className="font-mono text-[10px] text-muted-foreground">{member.occupancy}% ocupado</span></div><p className="font-heading text-lg font-semibold">{member.name}</p><p className="text-xs text-muted-foreground">{member.role}</p><Button asChild variant="link" className="mt-3 h-auto px-0"><Link href={`/barbearia/${business.slug}/agendar?profissional=${member.id}`}>Agendar com {member.name.split(" ")[0]} <ArrowRight data-icon="inline-end" /></Link></Button></CardContent></Card>)}</div></section>

      <section className="mx-auto max-w-7xl px-5 pb-20 lg:px-8"><Card className="overflow-hidden border-primary/20 bg-primary/8"><div className="grid lg:grid-cols-2"><CardHeader className="p-7 lg:p-10"><CardTitle className="font-heading text-3xl">Visite o clube.</CardTitle><CardDescription className="max-w-md text-sm leading-6">{business.address}. A dois minutos da Bourse, com estacionamento próximo.</CardDescription><div className="mt-6 flex flex-col gap-3 text-sm"><span className="flex gap-3"><Clock3 className="size-4 text-primary" /> Ter–Sex 09:00–19:00 · Sáb 09:00–18:00</span><span className="flex gap-3"><MapPin className="size-4 text-primary" /> {business.city}, Bélgica</span></div></CardHeader><div className="min-h-64 bg-[radial-gradient(circle_at_center,rgba(139,92,246,.3),transparent_4%),linear-gradient(135deg,transparent_45%,rgba(255,255,255,.05)_45%,rgba(255,255,255,.05)_48%,transparent_48%),#121217] bg-[length:auto,36px_36px]" aria-label="Mapa preparado do endereço da barbearia" /></div></Card></section>

      <footer className="border-t border-white/8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 sm:flex-row sm:items-center lg:px-8"><BrandMark /><p className="text-xs text-muted-foreground">© 2026 AS Barber Club · Privacidade · Cancelamentos</p></div></footer>
    </main>
  );
}
