import { Clock3, Sparkles } from "lucide-react";

import { WaitlistOfferButton } from "@/components/dashboard/waitlist-actions";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { waitlist } from "@/data/demo";

export default function WaitlistPage() {
  return <div className="flex flex-col gap-6"><section><p className="mb-2 text-xs font-medium uppercase tracking-[.18em] text-primary">Recuperação automática</p><h1 className="font-heading text-3xl font-semibold tracking-[-.035em]">Fila de espera</h1><p className="mt-2 text-sm text-muted-foreground">Transforme cancelamentos em oportunidades antes que a cadeira esfrie.</p></section><div className="grid gap-3 sm:grid-cols-3"><Card className="border-primary/20 bg-primary/5"><CardHeader className="pb-1"><CardDescription>Compatíveis agora</CardDescription></CardHeader><CardContent className="flex items-center justify-between"><p className="font-heading text-3xl font-semibold">3</p><Sparkles className="text-primary" /></CardContent></Card><Card><CardHeader className="pb-1"><CardDescription>Horários recuperados</CardDescription></CardHeader><CardContent><p className="font-heading text-3xl font-semibold">18</p></CardContent></Card><Card><CardHeader className="pb-1"><CardDescription>Receita recuperada</CardDescription></CardHeader><CardContent><p className="font-heading text-3xl font-semibold">€ 620</p></CardContent></Card></div><div className="grid gap-3">{waitlist.map((entry, index) => <Card key={entry.id} className="border-white/8"><CardContent className="grid gap-5 p-5 md:grid-cols-[1.2fr_1fr_.6fr_auto] md:items-center"><div><div className="flex items-center gap-2"><p className="font-medium">{entry.customer}</p><Badge variant={index === 0 ? "default" : "secondary"}>#{index + 1}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{entry.service}</p></div><div><p className="flex items-center gap-2 text-xs"><Clock3 className="size-3 text-primary" /> {entry.window}</p><p className="mt-1 text-[11px] text-muted-foreground">Antecedência mínima: {entry.notice}</p></div><div><div className="mb-2 flex justify-between text-[11px]"><span>Compatibilidade</span><span className="font-mono">{entry.compatibility}%</span></div><Progress value={entry.compatibility} /></div><WaitlistOfferButton customer={entry.customer} /></CardContent></Card>)}</div></div>;
}
